classdef CompositionalPhreeqcBatchTest < matlab.unittest.TestCase
    % Real COM regressions for cell mapping and solvent-H bookkeeping.
    properties
        model
        baseline
        batched
        preamble
    end
    methods (TestClassSetup)
        function simulateBothBatchLayouts(test)
            db=which('h2_biogeochemistry.dat');
            test.assumeTrue(ispc && ~isempty(db), ...
                'Windows IPhreeqcCOM and the bundled database are required.');
            [~,model,schedule,state0]=setupH2StorageExampleWithSRB_benchmark( ...
                'gridCells',4,'domainLength',5,'rate','highrate', ...
                'scheduleMode','complete','injectionCO2',0, ...
                'bacteriamodel',true,'bactDiffusion',false,'chemotaxisEffect',false, ...
                'molecularDiffusion',false,'molecularDispersion',false, ...
                'bioClogging',false,'carbonateBuffer',true, ...
                'carbonateBufferPH',6.24,'initialHCO3',1.370e-3, ...
                'initialOverallCO2',0,'equilibrateInitialCO2',false, ...
                'phreeqcTimestepCoupling',true, ...
                'phreeqcBackend','sequential-compositional-phreeqc', ...
                'phreeqcDatabaseFile',db,'sequentialCompositionalPhreeqcBatchSize',1);
            schedule.step.val=schedule.step.val(1:2);
            schedule.step.control=schedule.step.control(1:2);
            [~,test.baseline,report]=simulateScheduleAD(state0,model,schedule);
            assert(~report.Failure);
            test.model=model;
            % Independent setup avoids shared mutable EOS/state-function caches.
            [~,candidate,schedule,state0]=setupH2StorageExampleWithSRB_benchmark( ...
                'gridCells',4,'domainLength',5,'rate','highrate', ...
                'scheduleMode','complete','injectionCO2',0, ...
                'bacteriamodel',true,'bactDiffusion',false,'chemotaxisEffect',false, ...
                'molecularDiffusion',false,'molecularDispersion',false, ...
                'bioClogging',false,'carbonateBuffer',true, ...
                'carbonateBufferPH',6.24,'initialHCO3',1.370e-3, ...
                'initialOverallCO2',0,'equilibrateInitialCO2',false, ...
                'phreeqcTimestepCoupling',true, ...
                'phreeqcBackend','sequential-compositional-phreeqc', ...
                'phreeqcDatabaseFile',db,'sequentialCompositionalPhreeqcBatchSize',3);
            schedule.step.val=schedule.step.val(1:2);
            schedule.step.control=schedule.step.control(1:2);
            [~,test.batched,report]=simulateScheduleAD(state0,candidate,schedule);
            assert(~report.Failure);
            input=test.baseline{1}.sequentialCompositionalPhreeqcInputCell1String;
            index=strfind(input,sprintf('SOLUTION 1\n'));
            test.preamble=input(1:index(1)-1);
        end
    end
    methods (Test)
        function skippingInactiveCellsRetainsPhysicalStates(test)
            [~,candidate,schedule,state0]=setupH2StorageExampleWithSRB_benchmark( ...
                'gridCells',4,'domainLength',5,'rate','highrate', ...
                'scheduleMode','complete','injectionCO2',0, ...
                'bacteriamodel',true,'bactDiffusion',false,'chemotaxisEffect',false, ...
                'molecularDiffusion',false,'molecularDispersion',false, ...
                'bioClogging',false,'carbonateBuffer',true, ...
                'carbonateBufferPH',6.24,'initialHCO3',1.370e-3, ...
                'initialOverallCO2',0,'equilibrateInitialCO2',false, ...
                'phreeqcTimestepCoupling',true, ...
                'phreeqcBackend','sequential-compositional-phreeqc', ...
                'phreeqcDatabaseFile',which('h2_biogeochemistry.dat'), ...
                'sequentialCompositionalPhreeqcBatchSize',1);
            candidate.phreeqcCouplingOptions.sequentialCompositionalPhreeqcSkipInactiveCells=true;
            schedule.step.val=schedule.step.val(1:2); schedule.step.control=schedule.step.control(1:2);
            [~,actual,report]=simulateScheduleAD(state0,candidate,schedule);
            test.assertFalse(report.Failure);
            test.verifyTrue(all(actual{1}.sequentialCompositionalPhreeqcExecutedCells));
            test.verifyTrue(any(~actual{2}.sequentialCompositionalPhreeqcExecutedCells));
            for step=1:2
                for field={'pressure','components','x','y','s','phreeqcPH', ...
                    'tracerHCO3','tracerSO4','tracerHS','tracerCa','tracerMg', ...
                    'phreeqcMineralCalcite','phreeqcMineralDolomite', ...
                    'sequentialCompositionalPhreeqcReactionRates', ...
                    'sequentialCompositionalPhreeqcBiomassMET', ...
                    'sequentialCompositionalPhreeqcBiomassACE','sequentialCompositionalPhreeqcBiomassSRB'}
                    absolute=1e-7; if contains(field{1},'Biomass'), absolute=1e-13; end
                    test.verifyEqual(value(actual{step}.(field{1})),value(test.baseline{step}.(field{1})), ...
                        'AbsTol',absolute,'RelTol',1e-6,field{1});
                end
                mask=actual{step}.sequentialCompositionalPhreeqcExecutedCells;
                test.verifyEqual(actual{step}.phreeqcElementBalanceEvaluatedCells,mask);
                test.verifyEqual(actual{step}.phreeqcElementBalancePass(mask,:),test.baseline{step}.phreeqcElementBalancePass(mask,:));
                test.verifyTrue(all(isnan(actual{step}.sequentialCompositionalPhreeqcTDS(~mask))));
            end
            % A further no-injection, all-inactive chemistry split must also
            % preserve physical fields while making no COM/RATES calls.
            state=actual{2}; state.components(:,2)=0;
            state.components=state.components./sum(state.components,2);
            reference=candidate;
            reference.phreeqcCouplingOptions.sequentialCompositionalPhreeqcSkipInactiveCells=false;
            expected=runSequentialCompositionalPhreeqcCoupling(reference,state,day);
            observed=runSequentialCompositionalPhreeqcCoupling(candidate,state,day);
            test.verifyFalse(any(observed.sequentialCompositionalPhreeqcExecutedCells));
            for field={'pressure','components','s','phreeqcPH','tracerHCO3','tracerCa', ...
                'phreeqcMineralDolomite','sequentialCompositionalPhreeqcBiomassMET'}
                absolute=1e-7; if contains(field{1},'Biomass'), absolute=1e-13; end
                test.verifyEqual(value(observed.(field{1})),value(expected.(field{1})), ...
                    'AbsTol',absolute,'RelTol',1e-6,field{1});
            end
        end
        function batchedCellsRetainTheirChemistry(test)
            fields={'pressure','components','phreeqcPH', ...
                'tracerHCO3','tracerSO4','tracerHS','tracerCa','tracerMg', ...
                'phreeqcMineralCalcite','phreeqcMineralDolomite', ...
                'sequentialCompositionalPhreeqcReactionRates', ...
                'sequentialCompositionalPhreeqcBiomassMET', ...
                'sequentialCompositionalPhreeqcBiomassACE', ...
                'sequentialCompositionalPhreeqcBiomassSRB'};
            for step=1:2
                a=test.baseline{step}; b=test.batched{step};
                test.verifyTrue(all(a.phreeqcElementBalancePass(:,[1 2 4 5 6]),'all'));
                test.verifyTrue(all(b.phreeqcElementBalancePass(:,[1 2 4 5 6]),'all'));
                for field=fields
                    test.verifyEqual(value(a.(field{1})),value(b.(field{1})), ...
                        'AbsTol',1e-7,'RelTol',1e-6,field{1});
                end
            end
        end
        function acetateIncludesItsImplicitHydrogen(test)
            iph=actxserver(char(test.model.phreeqcComProgId));
            cleanup=onCleanup(@() delete(iph)); %#ok<NASGU>
            test.assertEqual(double(iph.LoadDatabase(test.model.phreeqcDatabaseFile)),0);
            % Add independent explicit-H and acetate-total observations to
            % the real production preamble, keeping its audited H unchanged.
            preamble=strrep(test.preamble,sprintf('REACTIVE_SYSTEM_H\n'), ...
                sprintf('REACTIVE_SYSTEM_H EXPLICIT_H ACETATE_MOLES\n'));
            preamble=strrep(preamble,sprintf('160 Punch reactiveh\n'), ...
                sprintf(['160 Punch reactiveh\n' ...
                '165 Punch SYS("H")-2*TOTMOLE("water"), TOT("Acetate")*TOT("water")\n']));
            input=[preamble,sprintf([ ...
                'SOLUTION 1\npH 7\nNa 0.1\nCl 0.1\nAcetate 0.01\n' ...
                'units mol/kgw\n-water 1\nEND\n'])];
            test.assertEqual(double(iph.RunString(input)),0);
            raw=iph.GetSelectedOutputArray;
            headers=cellfun(@(x) lower(regexprep(char(x),'[^a-zA-Z0-9]','')), ...
                raw(1,:),'UniformOutput',false);
            hydrogen=find(strcmp(headers,'reactivesystemh'),1);
            explicit=find(strcmp(headers,'explicith'),1);
            acetate=find(strcmp(headers,'acetatemoles'),1);
            test.assertNotEmpty(hydrogen); test.assertNotEmpty(explicit);
            test.assertNotEmpty(acetate);
            expected=raw{end,explicit}+3*raw{end,acetate};
            test.verifyEqual(raw{end,hydrogen},expected,'AbsTol',1e-7);
            test.verifyGreaterThan(raw{end,hydrogen},0.03);
        end

        function addedWaterContributesItsActualHydrogenMoles(test)
            iph=actxserver(char(test.model.phreeqcComProgId));
            cleanup=onCleanup(@() delete(iph)); %#ok<NASGU>
            test.assertEqual(double(iph.LoadDatabase(test.model.phreeqcDatabaseFile)),0);
            input=[test.preamble,sprintf([ ...
                'SOLUTION 1\npH 7\nNa 0.1\nCl 0.1\nunits mol/kgw\n-water 1\nEND\n' ...
                'REACTION 1\nH2O 1\n0.5 moles\nUSE solution 1\nUSE reaction 1\nEND\n'])];
            test.assertEqual(double(iph.RunString(input)),0);
            raw=iph.GetSelectedOutputArray;
            headers=cellfun(@(x) lower(regexprep(char(x),'[^a-zA-Z0-9]','')), ...
                raw(1,:),'UniformOutput',false);
            column=find(strcmp(headers,'reactivesystemh'),1);
            test.assertNotEmpty(column);
            % Half a mole of reaction water adds exactly one mole of H atoms.
            delta=raw{end,column}-raw{2,column};
            test.verifyEqual(delta,1,'AbsTol',1e-7);
        end
    end
end
